import sys
import binascii

#Open input file and get text table pointer
with open(sys.argv[1], "rb") as f:
    Index = f.seek(0xa2a0, 0)
    
    Pointer = str(binascii.hexlify(f.read(4), "-")).strip("'b").split("-")
    
#Convert pointer to address
    i = -1
    ret = ""
   
    while i >= -4:
        ret += Pointer[i]
        i -= 1
    
    ret = int(ret,16) - 0x8000000
        
#Write to event file    
with open("NewTextTable.event", "w") as f:
    f.write("//Generated by TableGetter\n")
    f.write("#define NewTextTable " + str(hex(ret)) + "\n")
    f.write("#define TextTable NewTextTable")
